# Generated by Django 4.0.5 on 2022-06-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_space_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.CharField(default=1, max_length=511),
            preserve_default=False,
        ),
    ]
