# Generated by Django 4.0.5 on 2022-06-22 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0008_subscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='space_slug',
            new_name='slug',
        ),
    ]
