# Generated by Django 4.0.5 on 2022-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0012_alter_subscription_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='is_member',
            field=models.BooleanField(default=False),
        ),
    ]
