# Generated by Django 4.0.5 on 2022-06-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0013_subscription_is_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_member',
            field=models.BooleanField(default=b'I01\n'),
        ),
    ]
