# Generated by Django 4.0.5 on 2022-06-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0014_alter_subscription_is_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='About',
            field=models.TextField(null=True),
        ),
    ]
