# Generated by Django 4.0.5 on 2022-06-23 20:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0016_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 2, 5, 14, 291126)),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('commented_on', models.DateTimeField(default=datetime.datetime(2022, 6, 24, 2, 5, 14, 292123))),
                ('Space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spaces.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
