# Generated by Django 4.0.5 on 2022-06-23 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0017_alter_posts_published_on_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'get_latest_by': 'published_on'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 3, 25, 12, 420433)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 3, 25, 12, 420433)),
        ),
    ]
