# Generated by Django 4.0.5 on 2022-06-24 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0019_comment_post_alter_comment_commented_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-commented_on',)},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-published_on',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 17, 4, 33, 952363)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 24, 17, 4, 33, 952363)),
        ),
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.CharField(max_length=511, null=True),
        ),
    ]
