# Generated by Django 4.0.5 on 2022-06-24 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0020_alter_comment_options_alter_posts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='secret_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 2, 43, 41, 318836)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 2, 43, 41, 318836)),
        ),
    ]
