# Generated by Django 4.0.5 on 2022-06-25 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0021_space_secret_code_alter_comment_commented_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 23, 7, 55, 596507)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='published_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 23, 7, 55, 595509)),
        ),
    ]
